import React, { createContext, useState, useContext } from 'react';

export const LanguageContext = createContext();

const translations = {
  en: {
    "Saguaro Link": "Saguaro Link",
    "Welcome": "Welcome",
    "Get Started": "Get Started",
    "Log Out": "Log Out",
    "Manage your health. Stay connected.": "Manage your health. Stay connected.",
    "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.": "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.",
    "Health Check-In": "Health Check-In",
    "Record your vitals, symptoms, and daily activity.": "Record your vitals, symptoms, and daily activity.",
    "Log Today": "Log Today",
    "Doctor Chat": "Doctor Chat",
    "Directly message your care team with questions or concerns.": "Directly message your care team with questions or concerns.",
    "Open Chat": "Open Chat",
    "My Logs": "My Logs",
    "Review your check-in history and track your health progress.": "Review your check-in history and track your health progress.",
    "View History": "View History",
    "Request a Ride": "Request a Ride",
    "Schedule or request transportation to your upcoming appointments.": "Schedule or request transportation to your upcoming appointments.",
    "Get a Ride": "Get a Ride",
    "Proactive Care": "Proactive Care",
    "Daily Health Monitor": "Daily Health Monitor",
    "General Wellbeing": "General Wellbeing",
    "How are you feeling today?": "How are you feeling today?",
    "Select mood...": "Select mood...",
    "Great": "Great",
    "Good": "Good",
    "Okay": "Okay",
    "Not great": "Not great",
    "Poor": "Poor",
    "Daily Activity": "Daily Activity",
    "I was physically active today": "I was physically active today",
    "Symptoms": "Symptoms",
    "I am experiencing symptoms today": "I am experiencing symptoms today",
    "Vitals & Readings": "Vitals & Readings",
    "Additional Notes": "Additional Notes",
    "Save Daily Check-In": "Save Daily Check-In",
    "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.": "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.",
    "Log In": "Log In",
    "Sign Up": "Sign Up",
    "Take Control of Your Health": "Take Control of Your Health",
    "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.": "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.",
    "Get Started Today": "Get Started Today",
    "Explore Banner Health": "Explore Banner Health",
    "Banner Health Resources": "Banner Health Resources",
    "Quick links to services and patient tools from Banner Health.": "Quick links to services and patient tools from Banner Health.",
    "Banner Health Services": "Banner Health Services",
    "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.": "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.",
    "Patients & Visitors": "Patients & Visitors",
    "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.": "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.",
    "Patient Account": "Patient Account",
    "Manage appointments, view records, message your care team, and request prescription renewals.": "Manage appointments, view records, message your care team, and request prescription renewals.",
    "Health & Wellness": "Health & Wellness",
    "Explore education, health checks, support groups, and prevention resources from Banner Health.": "Explore education, health checks, support groups, and prevention resources from Banner Health.",
    "Open Banner Health": "Open Banner Health",
    "Details": "Details",
    "(e.g. 30 min walk)": "(e.g. 30 min walk)",
    "What activity did you do?": "What activity did you do?",
    "Please describe your symptoms:": "Please describe your symptoms:",
    "e.g. Mild headache since morning, slight dizziness...": "e.g. Mild headache since morning, slight dizziness...",
    "Blood Pressure (Systolic / Diastolic)": "Blood Pressure (Systolic / Diastolic)",
    "Blood Glucose (mg/dL)": "Blood Glucose (mg/dL)",
    "Any other observations or concerns...": "Any other observations or concerns...",
    "Saving Check-In...": "Saving Check-In...",
    "Done": "Done",
    "✓ Check-in saved successfully!": "✓ Check-in saved successfully!",
    "Daily Tip": "Daily Tip",
    "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.": "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.",
    "Please check your inputs.": "Please check your inputs.",
    "You've already submitted a check-in for today.": "You've already submitted a check-in for today.",
    "Something went wrong. Please try again.": "Something went wrong. Please try again.",
    "Upcoming Rides": "Upcoming Rides",
    "To": "To",
    "From": "From",
    "Back": "Back",
    "Go back": "Go back",
    "My History Logs": "My History Logs",
    "No check-ins found. Start logging your daily health to see history here!": "No check-ins found. Start logging your daily health to see history here!",
    "Blood Sugar": "Blood Sugar",
    "Blood Pressure": "Blood Pressure",
    "Loading history...": "Loading history...",
    "Failed to load history logs.": "Failed to load history logs.",
    "Rewards & Streak": "Rewards & Streak",
    "Check your daily streak, earn points, and redeem them for rewards.": "Check your daily streak, earn points, and redeem them for rewards.",
    "View Rewards": "View Rewards",
    "Rewards & Incentives": "Rewards & Incentives",
    "Back to Dashboard": "Back to Dashboard",
    "Day": "Day",
    "Days": "Days",
    "Current Streak": "Current Streak",
    "Available Points": "Available Points",
    "My Balances": "My Balances",
    "Banner Bucks": "Banner Bucks",
    "Groceries Credit": "Groceries Credit",
    "Use for medication and groceries discounts": "Use for medication and groceries discounts",
    "Use for fresh groceries only": "Use for fresh groceries only",
    "Redeem Points": "Redeem Points",
    "Cost: 1000 Points": "Cost: 1000 Points",
    "Cost: 500 Points": "Cost: 500 Points",
    "Cost: 200 Points": "Cost: 200 Points",
    "Redeem": "Redeem",
    "Successfully redeemed": "Successfully redeemed",
    "Comprehensive Health Enrollment": "Comprehensive Health Enrollment",
    "Personal Information": "Personal Information",
    "Full Name": "Full Name",
    "Sex": "Sex",
    "Date of Birth": "Date of Birth",
    "Height (inches)": "Height (inches)",
    "Weight (lbs)": "Weight (lbs)",
    "Medical History": "Medical History",
    "Check all that apply to you:": "Check all that apply to you:",
    "Lifestyle & Habits": "Lifestyle & Habits",
    "I use tobacco or vaping products": "I use tobacco or vaping products",
    "I consume alcohol": "I consume alcohol",
    "Times per week:": "Times per week:",
    "Saving...": "Saving...",
    "Complete Enrollment": "Complete Enrollment",
    "Error saving profile. Please try again.": "Error saving profile. Please try again.",
    "Select...": "Select...",
    "Male": "Male",
    "Female": "Female",
    "Diabetes Type 1": "Diabetes Type 1",
    "Diabetes Type 2": "Diabetes Type 2",
    "Hypertension": "Hypertension",
    "COPD": "COPD",
    "Asthma": "Asthma",
    "Chronic Kidney Disease": "Chronic Kidney Disease",
    "Heart Disease": "Heart Disease",
    "Arthritis": "Arthritis",
    "Hyperlipidemia": "Hyperlipidemia",
    "Voice Input": "Voice Input",
    "Start Interactive Voice Check-in": "Start Interactive Voice Check-in",
    "Click 'Start Interactive Voice Check-in' to hear the questions. The microphone will start automatically after the questions are read. You can manually stop it when you're done.": "Click 'Start Interactive Voice Check-in' to hear the questions. The microphone will start automatically after the questions are read. You can manually stop it when you're done.",
    "Your voice input will appear here...": "Your voice input will appear here...",
    "Health Assistant Insight": "Health Assistant Insight",
    "Analyzing your daily check-in voice input...": "Analyzing your daily check-in voice input...",
    "I couldn't quite catch your blood sugar reading. Could you please say it again? (e.g., 'My sugar is 105')": "I couldn't quite catch your blood sugar reading. Could you please say it again? (e.g., 'My sugar is 105')",
    "Could not process your voice input into data. Please try speaking clearly or enter manually.": "Could not process your voice input into data. Please try speaking clearly or enter manually.",
    "Could not generate AI insight at this time.": "Could not generate AI insight at this time.",
    "None": "None",
    "Walking": "Walking",
    "Chores": "Chores",
    "Biking": "Biking",
    "Resting": "Resting",
    "Headache": "Headache",
    "Nausea": "Nausea",
    "Chest Pain": "Chest Pain",
    "Muscle Aches": "Muscle Aches",
    "Cough": "Cough",
    "🛑 Stop Mic": "🛑 Stop Mic",
    "🎤 Start Mic": "🎤 Start Mic",
    "How are you feeling today? Were you physically active today if so what did you do? Do you have any symptoms? If so what are they? How are your blood pressure and blood glucose readings?": "How are you feeling today? Were you physically active today if so what did you do? Do you have any symptoms? If so what are they? How are your blood pressure and blood glucose readings?",
    "Please configure your ElevenLabs API Key in the client code or .env first.": "Please configure your ElevenLabs API Key in the client code or .env first.",
    "Error communicating with ElevenLabs API. Please check your API Key and character limits.": "Error communicating with ElevenLabs API. Please check your API Key and character limits.",
    "Loading...": "Loading...",
    "Failed to load rewards data.": "Failed to load rewards data.",
    "Insufficient balance": "Insufficient balance",
    "Failed to redeem reward.": "Failed to redeem reward.",
    "Loading Rewards...": "Loading Rewards...",
    "Hello! I saw your glucose readings from this morning. How are you feeling?": "Hello! I saw your glucose readings from this morning. How are you feeling?",
    "I'm feeling okay, just a bit tired. I think my blood pressure was a little high too.": "I'm feeling okay, just a bit tired. I think my blood pressure was a little high too.",
    "Thank you for letting me know. Keep monitoring it and let's check in again tomorrow morning.": "Thank you for letting me know. Keep monitoring it and let's check in again tomorrow morning.",
    "Type a message to your doctor...": "Type a message to your doctor...",
    "Send": "Send",
    "Chatting with: ": "Chatting with: ",
    "Dr. Arispe": "Dr. Arispe",
    "Your Diabetes Management Portal": "Your Diabetes Management Portal",
    "Create an Account": "Create an Account",
    "Join Saguaro Link to start tracking your blood glucose and earning health credits.": "Join Saguaro Link to start tracking your blood glucose and earning health credits.",
    "Email Address": "Email Address",
    "Password": "Password",
    "At least 8 characters": "At least 8 characters",
    "Must be at least 8 characters and include a number.": "Must be at least 8 characters and include a number.",
    "Already have an account?": "Already have an account?",
    "Please log in": "Please log in",
    "Signing up...": "Signing up...",
    "Account created! Redirecting to login...": "Account created! Redirecting to login...",
    "Sign up failed. Please check your details and try again.": "Sign up failed. Please check your details and try again.",
    "Unable to start signup. Please check your Auth0 settings.": "Unable to start signup. Please check your Auth0 settings.",
    "Missing Auth0 config. Set REACT_APP_AUTH0_DOMAIN and REACT_APP_AUTH0_CLIENT_ID in client/.env.": "Missing Auth0 config. Set REACT_APP_AUTH0_DOMAIN and REACT_APP_AUTH0_CLIENT_ID in client/.env.",
    "Choose how you want to check in today": "Choose how you want to check in today",
    "Back to Home": "Back to Home",
    "Text Input": "Text Input",
    "Type your answers using the standard form.": "Type your answers using the standard form.",
    "Select Text": "Select Text",
    "Speech Input": "Speech Input",
    "Talk to the app to log your check-in automatically.": "Talk to the app to log your check-in automatically.",
    "Select Speech": "Select Speech",
    "Picture Mode": "Picture Mode",
    "Use simple images and emojis to answer the questions.": "Use simple images and emojis to answer the questions.",
    "Select Images": "Select Images"
  },
  es: {
    "Saguaro Link": "Saguaro Link",
    "Welcome": "Bienvenido",
    "Get Started": "Empezar",
    "Log Out": "Cerrar sesión",
    "Manage your health. Stay connected.": "Maneja tu salud. Mantente conectado.",
    "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.": "Registra tus signos vitales, síntomas y mantente en contacto con tu equipo de salud, todo en un solo lugar.",
    "Health Check-In": "Chequeo de Salud",
    "Record your vitals, symptoms, and daily activity.": "Registra tus signos vitales, síntomas y actividad diaria.",
    "Log Today": "Registrar Hoy",
    "Doctor Chat": "Chat con Médico",
    "Directly message your care team with questions or concerns.": "Envía mensajes a tu equipo médico con preguntas o inquietudes.",
    "Open Chat": "Abrir Chat",
    "My Logs": "Mis Registros",
    "Review your check-in history and track your health progress.": "Revisa tu historial y sigue el progreso de tu salud.",
    "View History": "Ver Historial",
    "Request a Ride": "Pedir Transporte",
    "Schedule or request transportation to your upcoming appointments.": "Programa o pide transporte para tus próximas citas.",
    "Get a Ride": "Pedir un Viaje",
    "Proactive Care": "Cuidado Proactivo",
    "Daily Health Monitor": "Monitor de Salud Diario",
    "General Wellbeing": "Bienestar General",
    "How are you feeling today?": "¿Cómo te sientes hoy?",
    "Select mood...": "Seleccionar estado...",
    "Great": "Excelente",
    "Good": "Bien",
    "Okay": "Regular",
    "Not great": "No muy bien",
    "Poor": "Mal",
    "Daily Activity": "Actividad Diaria",
    "I was physically active today": "Estuve físicamente activo hoy",
    "Symptoms": "Síntomas",
    "I am experiencing symptoms today": "Tengo síntomas hoy",
    "Vitals & Readings": "Signos Vitales",
    "Additional Notes": "Notas Adicionales",
    "Save Daily Check-In": "Guardar Chequeo Diario",
    "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.": "El seguimiento constante ayuda a identificar patrones y a manejar tu salud más eficazmente.",
    "Log In": "Iniciar sesión",
    "Sign Up": "Regístrate",
    "Take Control of Your Health": "Toma Control de tu Salud",
    "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.": "Registra tu salud diaria, monitorea síntomas y comparte información con tu equipo médico—todo en un solo lugar. Únete a Saguaro Link hoy y comienza tu camino hacia un mejor manejo de tu salud.",
    "Get Started Today": "Empieza Hoy",
    "Explore Banner Health": "Explorar Banner Health",
    "Banner Health Resources": "Recursos de Banner Health",
    "Quick links to services and patient tools from Banner Health.": "Enlaces rápidos a servicios y herramientas para pacientes de Banner Health.",
    "Banner Health Services": "Servicios de Banner Health",
    "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.": "Navega por opciones de atención primaria, atención de urgencia, imágenes, cirugía y medicina especializada.",
    "Patients & Visitors": "Pacientes y Visitantes",
    "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.": "Encuentra herramientas para pacientes como facturación, registros médicos, la aplicación de Banner, evaluador de síntomas y más.",
    "Patient Account": "Cuenta del Paciente",
    "Manage appointments, view records, message your care team, and request prescription renewals.": "Administra citas, ve registros, envía mensajes a tu equipo de salud y solicita renovaciones de recetas.",
    "Health & Wellness": "Salud y Bienestar",
    "Explore education, health checks, support groups, and prevention resources from Banner Health.": "Explora recursos de educación, chequeos de salud, grupos de apoyo y prevención de Banner Health.",
    "Open Banner Health": "Abrir Banner Health",
    "Details": "Detalles",
    "(e.g. 30 min walk)": "(ej. caminata de 30 min)",
    "What activity did you do?": "¿Qué actividad hiciste?",
    "Please describe your symptoms:": "Por favor, describe tus síntomas:",
    "e.g. Mild headache since morning, slight dizziness...": "ej. Dolor de cabeza leve desde la mañana, mareos...",
    "Blood Pressure (Systolic / Diastolic)": "Presión Arterial (Sistólica / Diastólica)",
    "Blood Glucose (mg/dL)": "Glucosa en Sangre (mg/dL)",
    "Any other observations or concerns...": "Cualquier otra observación o inquietud...",
    "Saving Check-In...": "Guardando Chequeo...",
    "Done": "Listo",
    "✓ Check-in saved successfully!": "✓ ¡Chequeo guardado exitosamente!",
    "Daily Tip": "Consejo Diario",
    "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.": "Registrar tus síntomas en detalle ayuda a tu proveedor de salud a comprender los desencadenantes y patrones en tu salud.",
    "Please check your inputs.": "Por favor, verifica tus datos.",
    "You've already submitted a check-in for today.": "Ya has enviado un chequeo para hoy.",
    "Something went wrong. Please try again.": "Algo salió mal. Por favor intenta de nuevo.",
    "Ride Details": "Detalles del Viaje",
    "Pickup Location": "Lugar de Recogida",
    "Enter pickup address": "Ingresa la dirección de recogida",
    "Destination": "Destino",
    "Enter destination address or clinic name": "Ingresa la dirección de destino o nombre de la clínica",
    "Schedule": "Horario",
    "Date": "Fecha",
    "Time": "Hora",
    "Accessibility & Notes": "Accesibilidad y Notas",
    "I require a wheelchair-accessible vehicle": "Necesito un vehículo accesible para silla de ruedas",
    "Reason for Visit / Additional Notes": "Motivo de la Visita / Notas Adicionales",
    "e.g. Doctor's appointment, need assistance at door...": "ej. Cita médica, necesito asistencia en la puerta...",
    "Requesting...": "Solicitando...",
    "Request Ride": "Pedir Transporte",
    "Cancel": "Cancelar",
    "✓ Ride requested successfully!": "✓ ¡Transporte solicitado exitosamente!",
    "Ride Information": "Información del Viaje",
    "Please be ready 15 minutes before your scheduled pickup time. The driver will wait up to 5 minutes.": "Por favor, esté listo 15 minutos antes de su hora de recogida programada. El conductor esperará hasta 5 minutos.",
    "Upcoming Rides": "Viajes Próximos",
    "To": "Hacia",
    "From": "Desde",
    "Back": "Volver",
    "Go back": "Regresar",
    "My History Logs": "Mi Historial",
    "No check-ins found. Start logging your daily health to see history here!": "No se encontraron registros. ¡Empieza a registrar tu salud diaria para ver tu historial aquí!",
    "Blood Sugar": "Nivel de Azúcar",
    "Blood Pressure": "Presión Arterial",
    "Loading history...": "Cargando historial...",
    "Failed to load history logs.": "Error al cargar el historial.",
    "Rewards & Streak": "Recompensas y Racha",
    "Check your daily streak, earn points, and redeem them for rewards.": "Revisa tu racha diaria, gana puntos y canjéalos por recompensas.",
    "View Rewards": "Ver Recompensas",
    "Rewards & Incentives": "Recompensas e Incentivos",
    "Back to Dashboard": "Volver al Panel",
    "Day": "Día",
    "Days": "Días",
    "Current Streak": "Racha Actual",
    "Available Points": "Puntos Disponibles",
    "My Balances": "Mis Saldos",
    "Banner Bucks": "Banner Bucks",
    "Groceries Credit": "Crédito para Compras",
    "Use for medication and groceries discounts": "Úselo para descuentos en medicamentos y víveres",
    "Use for fresh groceries only": "Úselo solo para víveres frescos",
    "Redeem Points": "Canjear Puntos",
    "Cost: 1000 Points": "Costo: 1000 Puntos",
    "Cost: 500 Points": "Costo: 500 Puntos",
    "Cost: 200 Points": "Costo: 200 Puntos",
    "Redeem": "Canjear",
    "Successfully redeemed": "Canjeado con éxito",
    "Comprehensive Health Enrollment": "Inscripción de Salud Integral",
    "Personal Information": "Información Personal",
    "Full Name": "Nombre Completo",
    "Sex": "Sexo",
    "Date of Birth": "Fecha de Nacimiento",
    "Height (inches)": "Altura (pulgadas)",
    "Weight (lbs)": "Peso (libras)",
    "Medical History": "Historial Médico",
    "Check all that apply to you:": "Marque todo lo que corresponda:",
    "Lifestyle & Habits": "Estilo de Vida y Hábitos",
    "I use tobacco or vaping products": "Uso tabaco o productos de vapeo",
    "I consume alcohol": "Consumo alcohol",
    "Times per week:": "Veces por semana:",
    "Saving...": "Guardando...",
    "Complete Enrollment": "Completar Inscripción",
    "Error saving profile. Please try again.": "Error al guardar el perfil. Por favor, inténtelo de nuevo.",
    "Select...": "Seleccionar...",
    "Male": "Masculino",
    "Female": "Femenino",
    "Diabetes Type 1": "Diabetes Tipo 1",
    "Diabetes Type 2": "Diabetes Tipo 2",
    "Hypertension": "Hipertensión",
    "COPD": "EPOC",
    "Asthma": "Asma",
    "Chronic Kidney Disease": "Enfermedad Renal Crónica",
    "Heart Disease": "Enfermedad Cardíaca",
    "Arthritis": "Artritis",
    "Hyperlipidemia": "Hiperlipidemia",
    "Voice Input": "Entrada de Voz",
    "Start Interactive Voice Check-in": "Iniciar Chequeo de Voz Interactivo",
    "Click 'Start Interactive Voice Check-in' to hear the questions. The microphone will start automatically after the questions are read. You can manually stop it when you're done.": "Haga clic en 'Iniciar Chequeo de Voz Interactivo' para escuchar las preguntas. El micrófono se iniciará automáticamente después de que se lean las preguntas. Puede detenerlo manualmente cuando haya terminado.",
    "Your voice input will appear here...": "Su entrada de voz aparecerá aquí...",
    "Health Assistant Insight": "Perspectiva del Asistente de Salud",
    "Analyzing your daily check-in voice input...": "Analizando su entrada de voz del chequeo diario...",
    "I couldn't quite catch your blood sugar reading. Could you please say it again? (e.g., 'My sugar is 105')": "No pude captar bien su lectura de azúcar en la sangre. ¿Podría repetirla? (ej. 'Mi azúcar es 105')",
    "Could not process your voice input into data. Please try speaking clearly or enter manually.": "No se pudo procesar su entrada de voz. Intente hablar con claridad o ingrese los datos manualmente.",
    "Could not generate AI insight at this time.": "No se pudo generar la perspectiva de la IA en este momento.",
    "None": "Ninguno",
    "Walking": "Caminar",
    "Chores": "Tareas domésticas",
    "Biking": "Ciclismo",
    "Resting": "Descansar",
    "Headache": "Dolor de cabeza",
    "Nausea": "Náuseas",
    "Chest Pain": "Dolor en el pecho",
    "Muscle Aches": "Dolores musculares",
    "Cough": "Tos",
    "🛑 Stop Mic": "🛑 Detener Mic",
    "🎤 Start Mic": "🎤 Iniciar Mic",
    "How are you feeling today? Were you physically active today if so what did you do? Do you have any symptoms? If so what are they? How are your blood pressure and blood glucose readings?": "¿Cómo se siente hoy? ¿Estuvo físicamente activo hoy, y si es así, qué hizo? ¿Tiene algún síntoma? Si es así, ¿cuáles son? ¿Cómo están sus lecturas de presión arterial y glucosa en sangre?",
    "Please configure your ElevenLabs API Key in the client code or .env first.": "Configure su clave API de ElevenLabs en el código del cliente o en el archivo .env primero.",
    "Error communicating with ElevenLabs API. Please check your API Key and character limits.": "Error al comunicarse con la API de ElevenLabs. Verifique su clave API y los límites de caracteres.",
    "Loading...": "Cargando...",
    "Failed to load rewards data.": "Error al cargar los datos de recompensas.",
    "Insufficient balance": "Saldo insuficiente",
    "Failed to redeem reward.": "Error al canjear la recompensa.",
    "Loading Rewards...": "Cargando Recompensas...",
    "Hello! I saw your glucose readings from this morning. How are you feeling?": "¡Hola! Vi tus lecturas de glucosa de esta mañana. ¿Cómo te sientes?",
    "I'm feeling okay, just a bit tired. I think my blood pressure was a little high too.": "Me siento bien, solo un poco cansado. Creo que mi presión arterial también estaba un poco alta.",
    "Thank you for letting me know. Keep monitoring it and let's check in again tomorrow morning.": "Gracias por avisarme. Sigue monitoreándolo y volvamos a hablar mañana por la mañana.",
    "Type a message to your doctor...": "Escribe un mensaje a tu médico...",
    "Send": "Enviar",
    "Chatting with: ": "Chateando con: ",
    "Dr. Arispe": "Dr. Arispe",
    "Your Diabetes Management Portal": "Tu Portal de Gestión de Diabetes",
    "Create an Account": "Crear una Cuenta",
    "Join Saguaro Link to start tracking your blood glucose and earning health credits.": "Únete a Saguaro Link para empezar a monitorear tu glucosa en sangre y ganar créditos de salud.",
    "Email Address": "Correo Electrónico",
    "Password": "Contraseña",
    "At least 8 characters": "Al menos 8 caracteres",
    "Must be at least 8 characters and include a number.": "Debe tener al menos 8 caracteres e incluir un número.",
    "Already have an account?": "¿Ya tienes una cuenta?",
    "Please log in": "Por favor inicia sesión",
    "Signing up...": "Registrándose...",
    "Account created! Redirecting to login...": "¡Cuenta creada! Redirigiendo al inicio de sesión...",
    "Sign up failed. Please check your details and try again.": "El registro falló. Por favor, verifica tus datos e inténtalo de nuevo.",
    "Unable to start signup. Please check your Auth0 settings.": "No se pudo iniciar el registro. Por favor, verifica tu configuración de Auth0.",
    "Missing Auth0 config. Set REACT_APP_AUTH0_DOMAIN and REACT_APP_AUTH0_CLIENT_ID in client/.env.": "Falta la configuración de Auth0. Establece REACT_APP_AUTH0_DOMAIN y REACT_APP_AUTH0_CLIENT_ID en client/.env.",
    "Choose how you want to check in today": "Elige cómo quieres registrarte hoy",
    "Back to Home": "Volver al Inicio",
    "Text Input": "Entrada de Texto",
    "Type your answers using the standard form.": "Escribe tus respuestas usando el formulario estándar.",
    "Select Text": "Seleccionar Texto",
    "Speech Input": "Entrada de Voz",
    "Talk to the app to log your check-in automatically.": "Habla con la aplicación para registrarte automáticamente.",
    "Select Speech": "Seleccionar Voz",
    "Picture Mode": "Modo de Imagen",
    "Use simple images and emojis to answer the questions.": "Usa imágenes simples y emojis para responder a las preguntas.",
    "Select Images": "Seleccionar Imágenes"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
