import React, { createContext, useState, useContext } from 'react';

export const LanguageContext = createContext();

const translations = {
  en: {
    "Saguaro Link": "Saguaro Link",
    "Welcome": "Welcome",
    "Get Started": "Get Started",
    "Log Out": "Log Out",
    "Manage your health. Stay connected.": "Manage your health. Stay connected.",
    "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.": "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.",
    "Health Check-In": "Health Check-In",
    "Record your vitals, symptoms, and daily activity.": "Record your vitals, symptoms, and daily activity.",
    "Log Today": "Log Today",
    "Doctor Chat": "Doctor Chat",
    "Directly message your care team with questions or concerns.": "Directly message your care team with questions or concerns.",
    "Open Chat": "Open Chat",
    "My Logs": "My Logs",
    "Review your check-in history and track your health progress.": "Review your check-in history and track your health progress.",
    "View History": "View History",
    "Request a Ride": "Request a Ride",
    "Schedule or request transportation to your upcoming appointments.": "Schedule or request transportation to your upcoming appointments.",
    "Get a Ride": "Get a Ride",
    "Proactive Care": "Proactive Care",
    "Daily Health Monitor": "Daily Health Monitor",
    "General Wellbeing": "General Wellbeing",
    "How are you feeling today?": "How are you feeling today?",
    "Select mood...": "Select mood...",
    "Great": "Great",
    "Good": "Good",
    "Okay": "Okay",
    "Not great": "Not great",
    "Poor": "Poor",
    "Daily Activity": "Daily Activity",
    "I was physically active today": "I was physically active today",
    "Symptoms": "Symptoms",
    "I am experiencing symptoms today": "I am experiencing symptoms today",
    "Vitals & Readings": "Vitals & Readings",
    "Additional Notes": "Additional Notes",
    "Save Daily Check-In": "Save Daily Check-In",
    "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.": "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.",
    "Log In": "Log In",
    "Sign Up": "Sign Up",
    "Take Control of Your Health": "Take Control of Your Health",
    "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.": "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.",
    "Get Started Today": "Get Started Today",
    "Explore Banner Health": "Explore Banner Health",
    "Banner Health Resources": "Banner Health Resources",
    "Quick links to services and patient tools from Banner Health.": "Quick links to services and patient tools from Banner Health.",
    "Banner Health Services": "Banner Health Services",
    "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.": "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.",
    "Patients & Visitors": "Patients & Visitors",
    "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.": "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.",
    "Patient Account": "Patient Account",
    "Manage appointments, view records, message your care team, and request prescription renewals.": "Manage appointments, view records, message your care team, and request prescription renewals.",
    "Health & Wellness": "Health & Wellness",
    "Explore education, health checks, support groups, and prevention resources from Banner Health.": "Explore education, health checks, support groups, and prevention resources from Banner Health.",
    "Open Banner Health": "Open Banner Health",
    "Details": "Details",
    "(e.g. 30 min walk)": "(e.g. 30 min walk)",
    "What activity did you do?": "What activity did you do?",
    "Please describe your symptoms:": "Please describe your symptoms:",
    "e.g. Mild headache since morning, slight dizziness...": "e.g. Mild headache since morning, slight dizziness...",
    "Blood Pressure (Systolic / Diastolic)": "Blood Pressure (Systolic / Diastolic)",
    "Blood Glucose (mg/dL)": "Blood Glucose (mg/dL)",
    "Any other observations or concerns...": "Any other observations or concerns...",
    "Saving Check-In...": "Saving Check-In...",
    "Done": "Done",
    "✓ Check-in saved successfully!": "✓ Check-in saved successfully!",
    "Daily Tip": "Daily Tip",
    "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.": "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.",
    "Please check your inputs.": "Please check your inputs.",
    "You've already submitted a check-in for today.": "You've already submitted a check-in for today.",
    "Something went wrong. Please try again.": "Something went wrong. Please try again.",
    "Upcoming Rides": "Upcoming Rides",
    "To": "To",
    "From": "From",
    "Back": "Back",
    "Go back": "Go back",
    "My History Logs": "My History Logs",
    "No check-ins found. Start logging your daily health to see history here!": "No check-ins found. Start logging your daily health to see history here!",
    "Blood Sugar": "Blood Sugar",
    "Blood Pressure": "Blood Pressure",
    "Loading history...": "Loading history...",
    "Failed to load history logs.": "Failed to load history logs.",
    "Rewards & Streak": "Rewards & Streak",
    "Check your daily streak, earn points, and redeem them for rewards.": "Check your daily streak, earn points, and redeem them for rewards.",
    "View Rewards": "View Rewards",
    "Rewards & Incentives": "Rewards & Incentives",
    "Back to Dashboard": "Back to Dashboard",
    "Day": "Day",
    "Days": "Days",
    "Current Streak": "Current Streak",
    "Available Points": "Available Points",
    "My Balances": "My Balances",
    "Banner Bucks": "Banner Bucks",
    "Groceries Credit": "Groceries Credit",
    "Use for medication and groceries discounts": "Use for medication and groceries discounts",
    "Use for fresh groceries only": "Use for fresh groceries only",
    "Redeem Points": "Redeem Points",
    "Cost: 1000 Points": "Cost: 1000 Points",
    "Cost: 500 Points": "Cost: 500 Points",
    "Cost: 200 Points": "Cost: 200 Points",
    "Redeem": "Redeem",
    "Successfully redeemed": "Successfully redeemed"
  },
  es: {
    "Saguaro Link": "Saguaro Link",
    "Welcome": "Bienvenido",
    "Get Started": "Empezar",
    "Log Out": "Cerrar sesión",
    "Manage your health. Stay connected.": "Maneja tu salud. Mantente conectado.",
    "Log your vitals, track symptoms, and stay in touch with your care team — all in one place.": "Registra tus signos vitales, síntomas y mantente en contacto con tu equipo de salud, todo en un solo lugar.",
    "Health Check-In": "Chequeo de Salud",
    "Record your vitals, symptoms, and daily activity.": "Registra tus signos vitales, síntomas y actividad diaria.",
    "Log Today": "Registrar Hoy",
    "Doctor Chat": "Chat con Médico",
    "Directly message your care team with questions or concerns.": "Envía mensajes a tu equipo médico con preguntas o inquietudes.",
    "Open Chat": "Abrir Chat",
    "My Logs": "Mis Registros",
    "Review your check-in history and track your health progress.": "Revisa tu historial y sigue el progreso de tu salud.",
    "View History": "Ver Historial",
    "Request a Ride": "Pedir Transporte",
    "Schedule or request transportation to your upcoming appointments.": "Programa o pide transporte para tus próximas citas.",
    "Get a Ride": "Pedir un Viaje",
    "Proactive Care": "Cuidado Proactivo",
    "Daily Health Monitor": "Monitor de Salud Diario",
    "General Wellbeing": "Bienestar General",
    "How are you feeling today?": "¿Cómo te sientes hoy?",
    "Select mood...": "Seleccionar estado...",
    "Great": "Excelente",
    "Good": "Bien",
    "Okay": "Regular",
    "Not great": "No muy bien",
    "Poor": "Mal",
    "Daily Activity": "Actividad Diaria",
    "I was physically active today": "Estuve físicamente activo hoy",
    "Symptoms": "Síntomas",
    "I am experiencing symptoms today": "Tengo síntomas hoy",
    "Vitals & Readings": "Signos Vitales",
    "Additional Notes": "Notas Adicionales",
    "Save Daily Check-In": "Guardar Chequeo Diario",
    "Consistent tracking helps Saguaro Link identify patterns and helps you manage your health more effectively.": "El seguimiento constante ayuda a identificar patrones y a manejar tu salud más eficazmente.",
    "Log In": "Iniciar sesión",
    "Sign Up": "Regístrate",
    "Take Control of Your Health": "Toma Control de tu Salud",
    "Track your daily health, monitor symptoms, and share insights with your care team—all in one place. Join Saguaro Link today and start your journey towards better health management.": "Registra tu salud diaria, monitorea síntomas y comparte información con tu equipo médico—todo en un solo lugar. Únete a Saguaro Link hoy y comienza tu camino hacia un mejor manejo de tu salud.",
    "Get Started Today": "Empieza Hoy",
    "Explore Banner Health": "Explorar Banner Health",
    "Banner Health Resources": "Recursos de Banner Health",
    "Quick links to services and patient tools from Banner Health.": "Enlaces rápidos a servicios y herramientas para pacientes de Banner Health.",
    "Banner Health Services": "Servicios de Banner Health",
    "Browse core care options like primary care, urgent care, imaging, surgery, and specialty medicine.": "Navega por opciones de atención primaria, atención de urgencia, imágenes, cirugía y medicina especializada.",
    "Patients & Visitors": "Pacientes y Visitantes",
    "Find patient tools such as billing, medical records, the Banner app, symptom checker, and more.": "Encuentra herramientas para pacientes como facturación, registros médicos, la aplicación de Banner, evaluador de síntomas y más.",
    "Patient Account": "Cuenta del Paciente",
    "Manage appointments, view records, message your care team, and request prescription renewals.": "Administra citas, ve registros, envía mensajes a tu equipo de salud y solicita renovaciones de recetas.",
    "Health & Wellness": "Salud y Bienestar",
    "Explore education, health checks, support groups, and prevention resources from Banner Health.": "Explora recursos de educación, chequeos de salud, grupos de apoyo y prevención de Banner Health.",
    "Open Banner Health": "Abrir Banner Health",
    "Details": "Detalles",
    "(e.g. 30 min walk)": "(ej. caminata de 30 min)",
    "What activity did you do?": "¿Qué actividad hiciste?",
    "Please describe your symptoms:": "Por favor, describe tus síntomas:",
    "e.g. Mild headache since morning, slight dizziness...": "ej. Dolor de cabeza leve desde la mañana, mareos...",
    "Blood Pressure (Systolic / Diastolic)": "Presión Arterial (Sistólica / Diastólica)",
    "Blood Glucose (mg/dL)": "Glucosa en Sangre (mg/dL)",
    "Any other observations or concerns...": "Cualquier otra observación o inquietud...",
    "Saving Check-In...": "Guardando Chequeo...",
    "Done": "Listo",
    "✓ Check-in saved successfully!": "✓ ¡Chequeo guardado exitosamente!",
    "Daily Tip": "Consejo Diario",
    "Recording your symptoms in detail helps your care provider understand triggers and patterns in your health.": "Registrar tus síntomas en detalle ayuda a tu proveedor de salud a comprender los desencadenantes y patrones en tu salud.",
    "Please check your inputs.": "Por favor, verifica tus datos.",
    "You've already submitted a check-in for today.": "Ya has enviado un chequeo para hoy.",
    "Something went wrong. Please try again.": "Algo salió mal. Por favor intenta de nuevo.",
    "Ride Details": "Detalles del Viaje",
    "Pickup Location": "Lugar de Recogida",
    "Enter pickup address": "Ingresa la dirección de recogida",
    "Destination": "Destino",
    "Enter destination address or clinic name": "Ingresa la dirección de destino o nombre de la clínica",
    "Schedule": "Horario",
    "Date": "Fecha",
    "Time": "Hora",
    "Accessibility & Notes": "Accesibilidad y Notas",
    "I require a wheelchair-accessible vehicle": "Necesito un vehículo accesible para silla de ruedas",
    "Reason for Visit / Additional Notes": "Motivo de la Visita / Notas Adicionales",
    "e.g. Doctor's appointment, need assistance at door...": "ej. Cita médica, necesito asistencia en la puerta...",
    "Requesting...": "Solicitando...",
    "Request Ride": "Pedir Transporte",
    "Cancel": "Cancelar",
    "✓ Ride requested successfully!": "✓ ¡Transporte solicitado exitosamente!",
    "Ride Information": "Información del Viaje",
    "Please be ready 15 minutes before your scheduled pickup time. The driver will wait up to 5 minutes.": "Por favor, esté listo 15 minutos antes de su hora de recogida programada. El conductor esperará hasta 5 minutos.",
    "Upcoming Rides": "Viajes Próximos",
    "To": "Hacia",
    "From": "Desde",
    "Back": "Volver",
    "Go back": "Regresar",
    "My History Logs": "Mi Historial",
    "No check-ins found. Start logging your daily health to see history here!": "No se encontraron registros. ¡Empieza a registrar tu salud diaria para ver tu historial aquí!",
    "Blood Sugar": "Nivel de Azúcar",
    "Blood Pressure": "Presión Arterial",
    "Loading history...": "Cargando historial...",
    "Failed to load history logs.": "Error al cargar el historial.",
    "Rewards & Streak": "Recompensas y Racha",
    "Check your daily streak, earn points, and redeem them for rewards.": "Revisa tu racha diaria, gana puntos y canjéalos por recompensas.",
    "View Rewards": "Ver Recompensas",
    "Rewards & Incentives": "Recompensas e Incentivos",
    "Back to Dashboard": "Volver al Panel",
    "Day": "Día",
    "Days": "Días",
    "Current Streak": "Racha Actual",
    "Available Points": "Puntos Disponibles",
    "My Balances": "Mis Saldos",
    "Banner Bucks": "Banner Bucks",
    "Groceries Credit": "Crédito para Compras",
    "Use for medication and groceries discounts": "Úselo para descuentos en medicamentos y víveres",
    "Use for fresh groceries only": "Úselo solo para víveres frescos",
    "Redeem Points": "Canjear Puntos",
    "Cost: 1000 Points": "Costo: 1000 Puntos",
    "Cost: 500 Points": "Costo: 500 Puntos",
    "Cost: 200 Points": "Costo: 200 Puntos",
    "Redeem": "Canjear",
    "Successfully redeemed": "Canjeado con éxito"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
